apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: second-namespace
spec:
  selector:
    matchLabels:
      name: "nginx"
  template:
    metadata:
      labels:
        name: "nginx"
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                - ALL
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      hostNetwork: true
      hostPID: true